W9/D3/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :new, :create, :edit, :update, :show]
end

W9/D3/ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord

    COLORS = ['brown', 'black', 'blue', 'grey', 'orange']
    
    validates :name, :birth_date, :color, :sex, :description, presence: true
    validates :color, inclusion: { in: COLORS }

    def self.colors
        COLORS
    end

    has_many :rental_requests,
        class_name: 'CatRentalRequest',
        foreign_key: :cat_id,
        dependent: :destroy
  
end

W9/D3/ninety_nine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: { in: ['PENDING', 'APPROVED', 'DENIED']}
    validate :does_not_overlap_approved_request

    belongs_to :cat,
        class_name: 'Cat',
        foreign_key: :cat_id

    def overlapping_requests
        
        CatRentalRequest  
            .where.not("start_date > '#{self.end_date}' OR
                end_date < '#{self.start_date}'")
            .where("cat_id = #{self.cat_id}")
            .where("status != 'DENIED'")
    end

    def overlapping_approved_requests
        overlapping_requests.where("status = 'APPROVED'")
    end

    def does_not_overlap_approved_request
        if overlapping_approved_requests.exists?
            errors.add(:start_date, "date overlaps with previously approved request")
            errors.add(:end_date, "date overlaps with previously approved request")
        end

    end
end

W9/D3/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def show
        @cat = Cat.find_by(id: params[:id])
        render :show 
    end

    def index 
        @cats = Cat.all 
        render :index
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)

        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end
    
    def edit
        @cat = Cat.find_by(id: params[:id])   
        render :edit
    end

    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    private
    def cat_params
        params.require(:cat).permit(:name, :sex, :birth_date, :color, :description)
    end

end

W9/D3/ninety_nine_cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat)%>
<% else %>
  <% action_url = cats_url %>
<% end %>




<form action=<%= action_url %> method="POST">

    <% if cat.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

  <label for="cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text" value=<%=cat.name%>>
  <br>

  <label for="cat_birth_date">Birth Date</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date" value=<%=cat.birth_date%>>
  <br>

  <label>Sex</label>
  <div>
 
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M"  <%=cat.sex == "M" ? "checked = true" : ""%>>
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F" <%=cat.sex == "F" ? "checked = true" : ""%>>
    <label for="cat_sex_f">Female</label>
  </div>
  <br>

  <label for="cat_description">Description</label>
  <textarea name="cat[description]" id="cat_description"><%=cat.description%></textarea>
  <br>

  <label for="cat_color">Color</label>

  <select name="cat[color]">
    <option disabled selected>-- Select Color --</option>
    <% Cat.colors.each do |color| %>
        <option value=<%= color %> <%= cat.color == color ? "selected" : ""%> ><%= color %></option>
    <% end %>
  </select>
  <br>


  <input type="submit" value="Update my cat!">
</form>

W9/D3/ninety_nine_cats/app/views/cats/edit.html.erb
<h2>Edit Cat</h2>
<%= render 'form', cat: @cat, action: :edit %>

W9/D3/ninety_nine_cats/app/views/cats/index.html.erb
<h1>Cats Index</h1>

<% @cats.each do |cat| %>
<ul> 
<li><a href="/cats/<%= cat.id %>"><%= cat.name %></a></li>
</ul>
<% end %>

W9/D3/ninety_nine_cats/app/views/cats/new.html.erb
<h2>New Cat</h2>
<%= render 'form', cat: @cat, action: :new %>

W9/D3/ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>





<table>
    <tbody>
        <tr>
            <td>Birthdate:</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Sex:</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Color:</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>


  